apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tutti

resources:
  - namespace.yaml
  - converter-service/deployment.yaml
  - converter-service/service.yaml

labels:
- pairs:
    project: tutti-platform
